site_name: "UVSQ_M2_NewSpace_TP_Python"
site_url: "https://nicoudart.github.io/UVSQ_M2_NewSpace_TP_Python"
site_author: "Nicolas OUDART"

theme:
  name: readthedocs
nav:
  - Accueil: index.md
  - 1. Contexte: 1_Contexte.md
  - 2. Mise en forme du module Python: 2_Module_python.md
  - 3. Lecture du fichier: 3_Lecture_fichier.md
  - 4. Traitement des données: 4_Traitement_donnees.md
  - 5. Export et affichage: 5_Export_affichage.md
  - 6. Exemples, tests et documentation: 6_Exemples_tests.md
  - 7. Documentation: 7_Documentation.md